<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Restaurantes extends \App\Entity\Restaurantes implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Correo' => [parent::class, 'Correo', null],
        "\0".parent::class."\0".'ciudad' => [parent::class, 'ciudad', null],
        "\0".parent::class."\0".'clave' => [parent::class, 'clave', null],
        "\0".parent::class."\0".'cp' => [parent::class, 'cp', null],
        "\0".parent::class."\0".'direccion' => [parent::class, 'direccion', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'pais' => [parent::class, 'pais', null],
        "\0".parent::class."\0".'pedidos' => [parent::class, 'pedidos', null],
        "\0".parent::class."\0".'rol' => [parent::class, 'rol', null],
        'Correo' => [parent::class, 'Correo', null],
        'ciudad' => [parent::class, 'ciudad', null],
        'clave' => [parent::class, 'clave', null],
        'cp' => [parent::class, 'cp', null],
        'direccion' => [parent::class, 'direccion', null],
        'id' => [parent::class, 'id', null],
        'pais' => [parent::class, 'pais', null],
        'pedidos' => [parent::class, 'pedidos', null],
        'rol' => [parent::class, 'rol', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
