<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHe0xt8V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHe0xt8V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHe0xt8V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHe0xt8V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHe0xt8V\App_KernelDevDebugContainer([
    'container.build_hash' => 'He0xt8V',
    'container.build_id' => '13d91729',
    'container.build_time' => 1709636134,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHe0xt8V');
